### ISSUE TITLE
Support MVV routes

### ISSUE THREAD

**Issue by mammuth** [pc-coholic/PyMVGLive#11]
Did anyone evaluate whether it's possible to also support routes within the MVV? 
There are a lot of (bus) routes which are not part of the MVG routes but of the MVV.

**Comment by pc-coholic** [comment]
Well... We're using the interface of www.mvg-live.de...

If it doesn't work on their website, it won't work for us either...

Or did I misunderstood what you're trying to say/do? :)

**Comment by mammuth** [comment]
The question was rather whether someone experimented whether there is something similar for the MVV. 

Btw, I found the following code snippet which uses a json api located at mvg.de: https://github.com/dfrommi/alfred-mvv/blob/master/src/mvg/api.py

I just scrolled through your code and it looks like you're scraping and parsing the results on the website? Using a json API might be easier to maintain. However, I don't know where the _X-MVG-Authorization-Key_ comes from and how it could be retrieved.

The API also exposes some more routes / departures than mvg-live.de

**Comment by pc-coholic** [comment]
Oh, okay - now I understand :-)

As far as I am aware, there is no such platform from the MVV yet - but I will keep my eyes peeled on that and update this if I obtain any new information.

Regarding the API:
I am not exactly scraping the webpage - there are people who do that, but that's mostly the mobile version of the website.

I am using an API, however it is not the official MVG Live API: it is a single-purpose webservice that has been created for the the mvg-live.de website, which in turn is created using [GWT](http://www.gwtproject.org/).

As GWT-Apps, front- and backend are written in Java and then compiled, the API is somewhat difficult to consume. In fact, it's not supposed to be consumed except by the GWT-application itself.

The project that you are linking is using the official MVG Live API. I do have an eMail-address somewhere, where one can request an API-key for using it. But the last time I checked with them, they considered their API as a premium product, requiring the payment of licensing fees for using the API.

So this project is just a cheap way around their payed API ;-) (Also, at the time of creation, I was not aware of any published key for the official API).

**Comment by mammuth** [comment]
Thanks for the information.
