### ISSUE TITLE
sys.exit()? Maybe use exeptions insteard

### ISSUE THREAD

**Issue by leftshift** [pc-coholic/PyMVGLive#5]
In some cases, the mvg servers return a "not //OK"
This causes the whole script to stop, which sometimes is quite inconvenient.
(I have a working implementation of this)

**Comment by pc-coholic** [comment]
Yeah, you are right - the current implementation is not really nice...

Please feel free to fork the repo and submit a pull-request - I'll be happy to merge it! :-)

**Comment by leftshift** [comment]
Uh, it seems like @weddige fixed this at some time in the past without me noticing ( #4 to be precise)
So nevermind, you can close this
