### ISSUE TITLE
Typo in PyPI file name

### ISSUE THREAD

**Issue by DavidMStraub** [pc-coholic/PyMVGLive#8]
There is a typo in the file name of version 1.1.2 on PyPI (an additional dot at the end, `1.1.2.`). This prevents installation with `pip install PyMVGLive==1.1.2` and also prevents upgrading from version 1.1.1 using `pip install --upgrade`. Could you please release a version 1.1.3 just correcting the file name? This will make using the library as a platform in Home Assistant easier (see [this PR](https://github.com/home-assistant/home-assistant/pull/6704)). Thanks!

**Comment by pc-coholic** [comment]
Hello David,

I just uploaded a 1.1.3 without the final dot at the end - please check if that works for you now.

**Comment by DavidMStraub** [comment]
Works, thanks!
